[notebook]
dir = "~/docs/zk"

[note]
language = "en"
default-title = "untitled"
filename = "{{id}}"
extension = "md"

[extra]
author = "rmr"

[format.markdown]
hashtags = true
colon-tags = true

[tool]
editor = "nvim"
shell = "/bin/bash"

[lsp]
[lsp.diagnostics]
wiki-title = "hint"
dead-link = "error"
